import pandas as pd
from fastapi import FastAPI
from contextlib import asynccontextmanager

alerts_cache = pd.DataFrame()


def load_alerts():
    """
    Load security alerts generated by Phase 4.
    """
    alerts_file = "data/alerts.csv"

    try:
        alerts = pd.read_csv(alerts_file)

        # Standardize column names
        alerts.columns = (
            alerts.columns
            .str.strip()
            .str.lower()
            .str.replace(" ", "_")
            .str.replace("-", "_")
        )

        print("Phase 4 alerts loaded successfully!")
        print(f"Total alerts loaded: {len(alerts)}")

        return alerts

    except FileNotFoundError:
        print("ERROR: data/alerts.csv not found!")
        print("Please run Phase 4 first.")
        return pd.DataFrame()

    except Exception as e:
        print(f"Error loading alerts: {e}")
        return pd.DataFrame()


@asynccontextmanager
async def lifespan(app: FastAPI):
    global alerts_cache

    alerts_cache = load_alerts()

    yield


app = FastAPI(
    title="SOC Alert Correlation and Incident Engine",
    lifespan=lifespan
)


@app.get("/")
def home():
    return {
        "status": "SOC Engine Running",
        "phase": "Phase 5 & Phase 6",
        "input": "data/alerts.csv",
        "endpoint": "/incidents"
    }


@app.get("/incidents")
def generate_incidents():

    if alerts_cache.empty:
        return {
            "error": "No alerts available.",
            "message": "Run Phase 4 first to generate data/alerts.csv"
        }

    # =========================================================
    # PHASE 5 - ALERT CORRELATION
    # =========================================================

    # Group alerts that belong to the same network activity.
    #
    # Alerts with the same:
    # source IP
    # destination IP
    # destination port
    #
    # are considered related.

    grouped_alerts = alerts_cache.groupby(
        ["source_ip", "destination_ip", "port"],
        sort=False
    )

    correlated_groups = []

    for correlation_idx, (
        (source_ip, destination_ip, port),
        group
    ) in enumerate(grouped_alerts, start=1):

        alert_ids = group["alert_id"].tolist()

        alert_types = (
            group["alert_type"]
            .dropna()
            .astype(str)
            .unique()
            .tolist()
        )

        correlation = {
            "correlation_id": f"CORR-{correlation_idx:03d}",
            "source_ip": str(source_ip),
            "destination_ip": str(destination_ip),
            "port": int(port),
            "alert_count": len(group),
            "alert_ids": alert_ids,
            "alert_types": alert_types,
            "first_timestamp": str(group["timestamp"].iloc[0]),
            "last_timestamp": str(group["timestamp"].iloc[-1])
        }

        correlated_groups.append(correlation)

    # =========================================================
    # PHASE 6 - INCIDENT FORMATION
    # =========================================================

    incidents = []

    for incident_idx, correlation in enumerate(
        correlated_groups,
        start=1
    ):

        alert_count = correlation["alert_count"]

        # Severity rules for the sample prototype
        if alert_count >= 5:
            severity = "CRITICAL"
        elif alert_count >= 2:
            severity = "HIGH"
        else:
            severity = "MEDIUM"

        # Get alerts belonging to this correlation group
        group = alerts_cache[
            (alerts_cache["source_ip"] == correlation["source_ip"]) &
            (alerts_cache["destination_ip"] == correlation["destination_ip"]) &
            (alerts_cache["port"] == correlation["port"])
        ]

        # Aggregate sample-data metrics
        total_packets = (
            int(group["packet_count"].sum())
            if "packet_count" in group.columns
            else 0
        )

        total_bytes = (
            int(group["byte_count"].sum())
            if "byte_count" in group.columns
            else 0
        )

        average_flow_duration = (
            float(group["flow_duration"].mean())
            if "flow_duration" in group.columns
            else 0.0
        )

        minimum_anomaly_score = (
            float(group["anomaly_score"].min())
            if "anomaly_score" in group.columns
            else 0.0
        )

        incident = {
            "incident_id": f"INC-{incident_idx:03d}",
            "correlation_id": correlation["correlation_id"],
            "source_ip": correlation["source_ip"],
            "destination_ip": correlation["destination_ip"],
            "port": correlation["port"],
            "severity": severity,
            "alert_count": alert_count,
            "alert_ids": correlation["alert_ids"],
            "alert_types": correlation["alert_types"],
            "metrics": {
                "total_packets": total_packets,
                "total_bytes": total_bytes,
                "average_flow_duration": round(
                    average_flow_duration,
                    2
                ),
                "minimum_anomaly_score": round(
                    minimum_anomaly_score,
                    6
                )
            }
        }

        incidents.append(incident)

    # Highest severity/activity first
    severity_order = {
        "CRITICAL": 3,
        "HIGH": 2,
        "MEDIUM": 1
    }

    incidents = sorted(
        incidents,
        key=lambda x: (
            severity_order[x["severity"]],
            x["alert_count"]
        ),
        reverse=True
    )

    return {
        "total_alerts": len(alerts_cache),
        "total_correlated_groups": len(correlated_groups),
        "total_incidents": len(incidents),
        "incidents": incidents
    }


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "main:app",
        host="127.0.0.1",
        port=8000,
        reload=True
    )
